FROM docker.elastic.co/elasticsearch/elasticsearch:6.6.1
LABEL maintainer Suzuka Asagiri <suzutan0s2@suzutan.jp>

RUN bin/elasticsearch-plugin install analysis-kuromoji
RUN bin/elasticsearch-plugin install analysis-icu
